//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPM.DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bidding()
        {
            this.CustomerBiddings = new HashSet<CustomerBidding>();
            this.ProviderBiddings = new HashSet<ProviderBidding>();
        }
    
        public int BiddingId { get; set; }
        public string Name { get; set; }
        public int LotId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> DocumentationId { get; set; }
        public int BiddingTypeId { get; set; }
        public int TenderTypeId { get; set; }
        public Nullable<int> ProtocolId { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual BiddingType BiddingType { get; set; }
        public virtual Country Country { get; set; }
        public virtual Document Document { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual TenderType TenderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBidding> CustomerBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderBidding> ProviderBiddings { get; set; }
        public virtual Person Person { get; set; }
    }
}
