//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPM.DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        public int BiddingId { get; set; }
        public string Name { get; set; }
        public int LotId { get; set; }
        public int PersonId { get; set; }
        public int DocumentationId { get; set; }
        public int BiddingTypeId { get; set; }
        public int TenderTypeId { get; set; }
        public int ProtocolId { get; set; }
    
        public virtual BiddingType BiddingType { get; set; }
        public virtual Document Document { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual Person Person { get; set; }
        public virtual Protocol Protocol { get; set; }
    }
}
