//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPM.DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FoundationDate { get; set; }
        public Nullable<int> INN { get; set; }
        public Nullable<int> KPP { get; set; }
        public Nullable<int> OGRN { get; set; }
        public Nullable<System.DateTime> AkkreditationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Persons { get; set; }
    }
}
