//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPM.DataModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradingPlatformManagementEntities : DbContext
    {
        public TradingPlatformManagementEntities()
            : base("name=TradingPlatformManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Bidding> Biddings { get; set; }
        public virtual DbSet<BiddingType> BiddingTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerBidding> CustomerBiddings { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<Protocol> Protocols { get; set; }
        public virtual DbSet<ProviderBidding> ProviderBiddings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenderType> TenderTypes { get; set; }
    }
}
